name: calendar_booking_app
description: Calendar Booking App for 1-on-1 counselling session between a Counsellor and a Student.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  moor: ^4.5.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0
  table_calendar: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  moor_generator: any
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
